trigger:
- main

pool:
  name: 'DDL-SSO'  # Replace with your agent pool name

steps:
- script: |
    # Define the URL for the SqlPackage installer
    $url = "https://aka.ms/sqlpackage"
    
    # Define the path to download the installer
    $installerPath = "$(System.DefaultWorkingDirectory)\SqlPackage.zip"
    
    # Download the SqlPackage installer
    Invoke-WebRequest -Uri $url -OutFile $installerPath
    
    # Unzip the installer
    Expand-Archive -Path $installerPath -DestinationPath "$(System.DefaultWorkingDirectory)\SqlPackage"
    
    # Add SqlPackage to the PATH
    $env:Path += ";$(System.DefaultWorkingDirectory)\SqlPackage"
    
    # Verify installation
    & "$(System.DefaultWorkingDirectory)\SqlPackage\SqlPackage.exe" /?
  displayName: 'Install SqlPackage'
  
- script: |
    # Your subsequent steps that use SqlPackage
    & "$(System.DefaultWorkingDirectory)\SqlPackage\SqlPackage.exe" /Action:Publish /SourceFile:"path_to_your_dacpac" /TargetConnectionString:"your_connection_string"
  displayName: 'Publish DACPAC'
